logging:
  level:
    com.line.service.spring.boot.linelogin: DEBUG

linecorp:
  platform:
    channel:
      channelId: '1653703435'
      channelSecret: 1de29b41b4411ff9832c4bba82fe3234
      callbackUrl: 'https://line12devlogin.herokuapp.com/auth'